
#
# This file is part of the `robfrawley/web-app` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this vinylSourceStream code.
#


#
# mailer configuration
#

swiftmailer:
    delivery_addresses:
        - "rf-web-app-dev@robfrawley.com"
