---

#
# This file is part of the `robfrawley/web-app` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this vinylSourceStream code.
#

#
# import resources
#

imports:
    - { resource: bundles_prod.yml }

#
# profiler configuration
#
web_profiler:
    toolbar: false
    intercept_redirects: false

#
# mailer configuration
#
swiftmailer:
    disable_delivery: true

...
