
#
# This file is part of the `robfrawley/web-app` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this vinylSourceStream code.
#


#
# default
#

app.default_view:
    path: /
    defaults:
        _controller: 'Rf\AppBundle\Controller\Index\ViewController'
    methods:
        - GET


#
# articles
#

app.articles_root:
    path: /articles
    defaults:
        _controller: 'Rf\AppBundle\Controller\Redirect\NamedRouteController'
        _redirect_name: app.articles_list
    methods:
        - GET

app.articles_view:
    path: /articles/view/{year}/{month}/{day}/{slug}
    defaults:
        _controller: 'Rf\AppBundle\Controller\Article\ViewController'
    methods:
        - GET

app.articles_permalink:
    path: /articles/view/{uuid}
    defaults:
        _controller: 'Rf\AppBundle\Controller\Article\ViewController'
    methods:
        - GET

app.articles_list:
    path: /articles/list
    defaults:
        _controller: 'Rf\AppBundle\Controller\Article\ListController'
    methods:
        - GET


#
# robots
#

app.robots_view:
    path: /robots.txt
    defaults:
        _controller: 'Rf\AppBundle\Controller\Robots\ViewController'
    methods:
        - GET


#
# sitemap
#

app.sitemap_root:
    path: /sitemap
    defaults:
        _controller: 'Rf\AppBundle\Controller\Redirect\NamedRouteController'
        _redirect_name: app.sitemap_view_xml
    methods:
        - GET

app.sitemap_view_xml:
    path: /sitemap.xml
    defaults:
        _controller: 'Rf\AppBundle\Controller\Sitemap\ViewXmlController'
    methods:
        - GET

app.sitemap_view_txt:
    path: /sitemap.txt
    defaults:
        _controller: 'Rf\AppBundle\Controller\Sitemap\ViewTxtController'
    methods:
        - GET


#
# slash redirect
#

app.redirect_remove_trailing_slash:
    path: /{url}
    defaults:
        _controller: 'Rf\AppBundle\Controller\Redirect\RemoveTrailingSlashController'
    requirements:
        url: .*/$
    methods:
        - GET
