Rf\AppBundle\Doctrine\Entity\Article:

    type: entity
    table: content_articles

    options:
        row_format: DYNAMIC
        charset: utf8mb4
        collate: utf8mb4_unicode_ci

    repositoryClass: Rf\AppBundle\Doctrine\Repository\ArticleRepository

    gedmo:
        loggable:
            logEntryClass: Rf\AppBundle\Doctrine\Entity\RevisionLog

    id:

        uuid:
            type: string
            length: 36
            id: true
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: SR\Doctrine\ORM\Id\StringUuid4PessimisticGenerator

    fields:

        slug:
            type: string
            length: 255
            gedmo:
                slug:
                    fields:
                        - title
                    updatable: true
                    unique: false
                    separator: -
                    style: lower

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create

        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update

        title:
            type: string
            length: 255
            gedmo:
                - versioned

        content:
            type: text
            gedmo:
                - versioned

    oneToMany:

        indices:
            targetEntity: Rf\AppBundle\Doctrine\Entity\SearchIndex
            mappedBy: article
            fetch: LAZY
